### ISSUE TITLE
Why use the R and C of GroundTruth for computing the D1C and D2C ? they are the goals of this question.

### ISSUE THREAD

**Issue by Zedzou** [pmiraldo/MinimalMultiPerspectivePose#1]
In the GetData.m of the p2l1, line 38 41 and ... . using the GroundTruth R C for computing the D1C and the D2C, and in the compute_1lp2,  taking the D1C and D2C as the input for computing the pose. 
But R and C is the goal of this arithmetic, we dont know the R and the C, how to computing the pose?

**Comment by pmiraldo** [comment]
Hi,

Thank you for your email.

The purpose of the GetData.m function is to provide the data (2D-3D points and lines) and the ground truth transformation. It basically returns the adapter, which contains the 2D-3D correspondences, and the R and C that are the ground truth rotation and translation.

The compute_1lp2 computes the pose and only gets as input the adapter, as shown in the paper. Results will be compared to R and C in the run_2p1l, the compute_1lp2 doesn't know what is the R and C.

Does this help?

Thanks,
Pedro

**Comment by Zedzou** [comment]
> Hi,
> 
> Thank you for your email.
> 
> The purpose of the GetData.m function is to provide the data (2D-3D points and lines) and the ground truth transformation. It basically returns the adapter, which contains the 2D-3D correspondences, and the R and C that are the ground truth rotation and translation.
> 
> The compute_1lp2 computes the pose and only gets as input the adapter, as shown in the paper. Results will be compared to R and C in the run_2p1l, the compute_1lp2 doesn't know what is the R and C.
> 
> Does this help?
> 
> Thanks,
> Pedro

**Comment by Zedzou** [comment]
> Hi,
> 
> Thank you for your email.
> 
> The purpose of the GetData.m function is to provide the data (2D-3D points and lines) and the ground truth transformation. It basically returns the adapter, which contains the 2D-3D correspondences, and the R and C that are the ground truth rotation and translation.
> 
> The compute_1lp2 computes the pose and only gets as input the adapter, as shown in the paper. Results will be compared to R and C in the run_2p1l, the compute_1lp2 doesn't know what is the R and C.
> 
> Does this help?
> 
> Thanks,
> Pedro

Hi，
Thank you very much for your reply and help.

**Comment by Zedzou** [comment]
Hi, Professor Pedro,

Thank you very much for your reply and help. Your paper and code have been very helpful to me, Thank you very much. But I just don't understand one thing in the code, So take the liberty to come for advice.

For example, in the project p2l1.
The GetData.m , The code for calculating D1C and D2C in line 37-41, as follows.
`
1. C1C = [0;5;0]+randn(3,1)*2;
2. C1W = R*C1C + C;
3. D1W = P1-C1W; D1W = D1W/norm(D1W);
4. D1C = R'*D1W; D1C = D1C/norm(D1C);
`

and then In line 88-90, setting the adapter.

`
1. adapter.camera.d1 = D1C;
2. adapter.camera.d2 = D2C
;`


In compute_1lp2.m , getting data from the adapter.

`
1. D1 = adapter.camera.d1;
2. D2 = adapter.camera.d2
;`


and using the D1 and D2 for Later calculation of pose estimaton.
`
1. % D2
2. d11 = e11*D1(1) + e12*D1(2) + e13*D1(3);
3. d12 = e21*D1(1) + e22*D1(2) + e23*D1(3);
4. d13 = e31*D1(1) + e32*D1(2) + e33*D1(3);
5. % D2
6. d21 = e11*D2(1) + e12*D2(2) + e13*D2(3);
7. d22 = e21*D2(1) + e22*D2(2) + e23*D2(3);
8. d23 = e31*D2(1) + e32*D2(2) + e33*D2(3)
;`

So, I'm confused about that and think compute_1lp2.m has using the data computed by the GroundTruth R and C.  and I don't know where I misunderstood. Looking forward to your reply very much. Thank you.

Thanks,

**Comment by Zedzou** [comment]
Hi, Professor Pedro,

Thank you very much for your reply and help. Your paper and code have been very helpful to me, Thank you very much. But I just don't understand one thing in the code, So take the liberty to come for advice.

For example, in the project p2l1.
The GetData.m , The code for calculating D1C and D2C in line 37-41 , as follows.
`
37. C1C = [0;5;0]+randn(3,1)*2;
38. C1W = R*C1C + C;
39. D1W = P1-C1W; D1W = D1W/norm(D1W);
40. D1C = R'*D1W; D1C = D1C/norm(D1C);
`
In line 38 and 40, using the R and C for computing the C1W and D1C.

And then In line 88-90, setting the adapter.
`
88. adapter.camera.d1 = D1C;
89. adapter.camera.d2 = D2C;
`

But in compute_1lp2.m , getting data from the adapter.
`
D1 = adapter.camera.d1;
D2 = adapter.camera.d2;
`
and using the D1 and D2 for Later calculation of pose estimaton.
`
% D2
d11 = e11D1(1) + e12D1(2) + e13*D1(3);
d12 = e21D1(1) + e22D1(2) + e23*D1(3);
d13 = e31D1(1) + e32D1(2) + e33*D1(3);
% D2
d21 = e11D2(1) + e12D2(2) + e13*D2(3);
d22 = e21D2(1) + e22D2(2) + e23*D2(3);
d23 = e31D2(1) + e32D2(2) + e33*D2(3);
`
So, I'm confused about that and think compute_1lp2.m has using the data computed by the GroundTruth R and C. and I don't know where I misunderstood. Looking forward to your reply very much. Thank you.

Thanks,

**Comment by Zedzou** [comment]
Hi, Professor Pedro,

Thank you very much for your reply and help. Your paper and code have been very helpful to me, Thank you very much. But I just don't understand one thing in the code, So take the liberty to come for advice.

For example, in the project p2l1.
The GetData.m , The code for calculating C1W and D1C in line 37-40 , as follows.
```
37. C1C = [0;5;0]+randn(3,1)*2; 
38. C1W = R*C1C + C; 
39. D1W = P1-C1W; D1W = D1W/norm(D1W); 
40. D1C = R'*D1W; D1C = D1C/norm(D1C);
```
In line 38 and 40, using the R and C for computing the C1W and D1C.
And then In line 88-90, setting the adapter.
```
88. adapter.camera.d1 = D1C; 
89. adapter.camera.d2 = D2C;
```

But in compute_1lp2.m , getting data from the adapter.
```
21. D1 = adapter.camera.d1; 
22. D2 = adapter.camera.d2;
```
and using the D1 and D2 for Later calculation of pose estimaton.
```
% D2 
d11 = e11D1(1) + e12D1(2) + e13*D1(3); 
d12 = e21D1(1) + e22D1(2) + e23*D1(3); 
d13 = e31D1(1) + e32D1(2) + e33*D1(3); 
% D2 
d21 = e11D2(1) + e12D2(2) + e13*D2(3); 
d22 = e21D2(1) + e22D2(2) + e23*D2(3); 
d23 = e31D2(1) + e32D2(2) + e33*D2(3);
```
So, I'm confused about that and think compute_1lp2.m has using the data (D1 D2)computed by the GroundTruth R and C. and I don't know where I misunderstood. Looking forward to your reply very much. Thank you.

Thanks,

**Comment by pmiraldo** [comment]
Hi,

Sorry for the later reply. I was busy with some submissions.

Of course, I am using D1, and D2 computed with the GroundTruth (GT). That doesn't mean I am using the GT R and C in the computation of the pose (estimation of R and C). To generate the data, I have to use some GT R, and C. Notice these are tests with simulated data, I have to create D1 and D2 and have R and C to compare the estimated solution with the one given by the solver. That is what I am doing in the generated data. But, again, the adapter, which is the input for the estimator, doesn't include the GT R and C.

Hope it clarifies your issues. Let me know if you are still struggling with this.

Thanks,
Pedro

**Comment by Zedzou** [comment]
Hi, professor

Thank you for your guidance，I have understood the effect of GT, Thank you very much.  

But when testing with the real data, that we only know the world coordinates of 3D points and the Pixel coordinates of 2D Points, don't know any information of the GT. how to compute the D1 and D2.  

I just don't konw how to compute the D1 and D2 in the real data.  Sorry to trouble you and hope you could give me some guidance of this question. Thank you very much.

Thanks,
Zed
